### ISSUE TITLE
This paper seems to be the same as O-LoRA 

### ISSUE THREAD

**Issue by BeyonderXX** [liangyanshuo/InfLoRA#2]
你好！
我们2023年发表了一篇论文，被EMNLP2023接收，题为：
[Orthogonal Subspace Learning for Language Model Continual Learning](https://arxiv.org/pdf/2310.14152.pdf)

发现和你的论文非常相似，建议增加对比说明。谢谢！

Xiao Wang

**Comment by liangyanshuo** [comment]
你好，我拜读了贵组的文章，和我们的工作完全不一样。
贵组的O-LoRA是每一个任务维护一组lora参数，不同任务的lora参数保持正交。
我们的InfLoRA是维护一个投影矩阵，保证新任务的lora参数和旧任务的输入保持正交。
这两种方式在数学上是完全不同的，因此说我们的InfLoRA和O-LoRA一样是不太合适的。

**Comment by kun-dragon** [comment]
所以，O-LoRA论文的Figure1中“O-LoRA mitigates catastrophic forgetting of past task knowledge by constraining the gradient updates of the current task to be orthogonal to the gradient subspace of the past tasks.” 提到的梯度更新与过去任务的梯度子空间正交的描述是不准确的。其只保证了不同任务的lora参数矩阵的正交。可以这样理解吗？
