### ISSUE TITLE
Reproduction on DomainNet

### ISSUE THREAD

**Issue by coyoteling** [liangyanshuo/InfLoRA#3]
Hello, all
I noticed that the processing of DomainNet in your code contains two files "dataloaders/splits/domainnet_train.yaml" and "dataloaders/splits/domainnet_test.yaml" , but you didn't provide them in your public code, 
can you please provide these two files?
Thanks a lot!

**Comment by liangyanshuo** [comment]
Hello,
  "dataloaders/splits/domainnet_train.yaml" and "dataloaders/splits/domainnet_test.yaml" are borrowed from the work CODA prompt (https://github.com/GT-RIPL/CODA-Prompt). I have updated the code, making it include these two files.

**Comment by kandeldeepak46** [comment]
Hi @coyoteling ,

Are you able to run the simulation in CIFAR-100?

I am getting the following error
![image](https://github.com/liangyanshuo/InfLoRA/assets/33603333/83c9f017-3db4-4dee-93ef-6ffe7443a188)
```python
python main.py --device 0 --config configs/cifar100_inflora.json 
```
Could you please help me to resolve the issue? I ran above command

Thank you!
