### ISSUE TITLE
Issue with CIFAR100

### ISSUE THREAD

**Issue by kandeldeepak46** [liangyanshuo/InfLoRA#4]
Hi Authors,

Thank you for your great contribution in CL

I am trying to reproduce the code. Could you please help me to solve the following issue?

Thank you

![image](https://github.com/liangyanshuo/InfLoRA/assets/33603333/fb32328a-9a3a-4043-a962-8e5c3d781512)

**Comment by liangyanshuo** [comment]
Sorry for the late reply. It appears that some Python modules have incompatible versions with the code. Please try installing the following module versions:
torch: 1.10.0
torchvision: 0.11.1
timm: 0.6.7
